In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.datasets import load_iris
from sklearn.cluster import KMeans

In [13]:
data = load_iris()

In [14]:
X = data.data
label = data.target

In [15]:
data.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

# k-means by sklearn

In [16]:
kmeans = KMeans(n_clusters = 3, init = 'k-means++', random_state = 1)
pred = kmeans.fit_predict(X)

In [17]:
pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2,
       2, 2, 2, 0, 0, 2, 2, 2, 2, 0, 2, 0, 2, 0, 2, 2, 0, 0, 2, 2, 2, 2,
       2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 0], dtype=int32)

In [18]:
label

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

# k-means

* https://aizine.ai/clustering0522/
* https://www.medi-08-data-06.work/entry/kmeans
* https://ja.wikipedia.org/wiki/K平均法
* http://www.cs.uoi.gr/%7Early/papers/TNN09b.pdf

In [19]:
center = X[np.random.choice(X.shape[0], 5)]

In [20]:
distance = np.sum((center -X[0])**2, axis=1)

In [21]:
distance

array([ 0.15, 19.89, 38.94, 26.23, 23.01])

In [22]:
cluster = np.zeros(X.shape[0])

In [23]:
cluster[0] = np.argsort(distance[0])

In [24]:
cluster

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
def kmeans(X,K,centers,iter):
    #Xのサンプル数だけ空のラベルを作る
    idx = np.zeros(X.shape[0])
    sse = np.zeros(K)
    for _ in range(iter):
        #距離の二乗が一番近い中心点のインデックスを返す。
        for i in range(X.shape[0]):
            #セントロイドとの距離を求める
            distance = np.sum((X[i,:] - centers)**2, axis=1)
            #距離の近いindexがラベル
            idx[i] = np.argmin(distance)
            
        #セントロイドの移動
        for k in range(K):
            centers[k,:] = X[idx==k,:].mean(axis=0)
            sse[k] = np.sum((X[idx==k,:]-centers[k,:])**2)
    
    sse_sum = np.sum(sse)#全てのクラスで合計する
    
    return idx, sse_sum, centers

In [30]:
np.argmin(np.sum((X[1,:] - center)**2, axis=0))

1

In [31]:
center = X[np.random.choice(X.shape[0], 3)]

In [32]:
pred, sse, center = kmeans(X, 3, center, 300)

In [33]:
center

array([[5.006     , 3.428     , 1.462     , 0.246     ],
       [6.85384615, 3.07692308, 5.71538462, 2.05384615],
       [5.88360656, 2.74098361, 4.38852459, 1.43442623]])

In [34]:
pred

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       2., 1., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 1., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 1., 2.,
       1., 1., 1., 1., 2., 1., 1., 1., 1., 1., 1., 2., 2., 1., 1., 1., 1.,
       2., 1., 2., 1., 2., 1., 1., 2., 2., 1., 1., 1., 1., 1., 2., 1., 1.,
       1., 1., 2., 1., 1., 1., 2., 1., 1., 1., 2., 1., 1., 2.])

In [35]:
sse

78.8556658259773

# Fuzzy c-means

## 参考: http://ibisforest.org/index.php?ファジィc-means法
1. 初期化：{uki} をランダムに初期化
2. 現在の {uki} を用いて，各クラスタの中心 μk を次式で計算
3. 前ステップで計算した中心 {μk} を用いて，事例 xi のクラスタ k への割り当てを次式で更新

$$\boldsymbol{\mu}_k=\frac{\sum_i^N (u_{ki})^m \mathbf{x}_i}{\sum_i^N (u_{ki})^m}$$

$$u_{ki}=\Biggl[\sum_j^c \biggl(\frac{\|\mathbf{x}_i-\boldsymbol{\mu}_k\|}{\|\mathbf{x}_i-\boldsymbol{\mu}_j\|}\biggr)^{\frac{2}{m-1}}\Biggr]^{-1}$$

* http://www.cs.osakafu-u.ac.jp/hi/honda/fcm.htm
* https://home.deib.polimi.it/matteucc/Clustering/tutorial_html/cmeans.html