# MNIST画像　グレースケール　0~1.0

In [48]:
import numpy as np
#データの読み込みと前処理
from keras.utils import np_utils
from keras.datasets import mnist
#kerasでCNN構築
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D
from keras.layers import Activation, Dropout, Flatten, Dense
from keras.optimizers import Adam
#時間計測
import time
 
 
'''
データの読み込みと前処理
'''
#データの読み込み
(X_train, y_train), (X_test, y_test) = mnist.load_data()
 
#訓練データ
X_train = X_train.reshape(60000, 28, 28, 1)
X_train = X_train.astype('float32')#型を変更
X_train /= 255 #0から1.0の範囲に変換
print(X_train.max())
print(type(X_train[0][0][0][0]))
#正解ラベル
correct = 10
y_train = np_utils.to_categorical(y_train, correct)
 
#テストデータ
X_test = X_test.reshape(10000, 28, 28, 1)
X_test = X_test.astype('float32')
X_test /= 255
 
y_test = np_utils.to_categorical(y_test, correct)


1.0
<class 'numpy.float32'>
[[[0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]]

 [[0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]]

 [[0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.   

In [2]:
 
'''
CNNの構築
'''
 
model = Sequential()
 
model.add(Conv2D(filters=32, kernel_size=(3,3), padding='same', input_shape=(28, 28, 1), activation='relu'))
model.add(Flatten())
model.add
model.add(Dense(10, activation='softmax'))
 
model.compile(loss='categorical_crossentropy', optimizer=Adam(), metrics=['accuracy'])
 
'''
学習
'''
#計測開始
startTime = time.time()
 
history = model.fit(X_train, y_train, epochs=1, batch_size=100, verbose=1, validation_data=(X_test, y_test))
 
score = model.evaluate(X_test, y_test, verbose=0)
timer = time.time() - startTime
print('Test Loss:{0:.3f}'.format(score[0]))
print('Test accuracy:{0:.3}'.format(score[1]))
#処理時間
print("time:{0:.3f}sec".format(timer))

Train on 60000 samples, validate on 10000 samples
Epoch 1/20
60000/60000 [==============================] - 15s 245us/step - loss: 0.2335 - acc: 0.9335 - val_loss: 0.1010 - val_acc: 0.9725.2460 - ETA: 0s - loss: 0.2363 - acc: 0
Epoch 2/20
60000/60000 [==============================] - 15s 252us/step - loss: 0.0813 - acc: 0.9764 - val_loss: 0.0674 - val_acc: 0.9782
Epoch 3/20
60000/60000 [==============================] - 17s 277us/step - loss: 0.0581 - acc: 0.9830 - val_loss: 0.0633 - val_acc: 0.9801
Epoch 4/20
60000/60000 [==============================] - 15s 244us/step - loss: 0.0458 - acc: 0.9864 - val_loss: 0.0579 - val_acc: 0.9814
Epoch 5/20
60000/60000 [==============================] - 15s 246us/step - loss: 0.0370 - acc: 0.9890 - val_loss: 0.0631 - val_acc: 0.9807
Epoch 6/20
60000/60000 [==============================] - 15s 246us/step - loss: 0.0304 - acc: 0.9910 - val_loss: 0.0602 - val_acc: 0.981700 - acc:  - ETA: 1s - 
Epoch 7/20
60000/60000 [==============================

In [5]:
with open('sample.txt', 'w') as f:
  # 書き込み
  f.writelines('Test Loss:{0:.3f}'.format(score[0])+"\n")
  f.writelines('Test accuracy:{0:.3}'.format(score[1])+"\n")
  f.writelines("time:{0:.3f}sec".format(timer)+)

# MNIST画像　グレースケール　0~255.0

In [49]:
 
'''
データの読み込みと前処理
'''
#データの読み込み
(X_train, y_train), (X_test, y_test) = mnist.load_data()
#訓練データ
X_train = X_train.reshape(60000, 28, 28, 1)
X_train = X_train.astype('float32')#型を変更
#X_train /= 255 #0から1.0の範囲に変換
 
#正解ラベル
correct = 10
y_train = np_utils.to_categorical(y_train, correct)
 
#テストデータ
X_test = X_test.reshape(10000, 28, 28, 1)
X_test = X_test.astype('float32')
#X_test /= 255
 
y_test = np_utils.to_categorical(y_test, correct)

print(X_train[0])

[[[  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]]

 [[  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]]

 [[  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]]

 [[  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [ 

In [10]:
'''
CNNの構築
'''
 
model = Sequential()
 
model.add(Conv2D(filters=32, kernel_size=(3,3), padding='same', input_shape=(28, 28, 1), activation='relu'))
model.add(Flatten())
model.add
model.add(Dense(10, activation='softmax'))
 
model.compile(loss='categorical_crossentropy', optimizer=Adam(), metrics=['accuracy'])
 
'''
学習
'''
#計測開始
startTime = time.time()
 
history = model.fit(X_train, y_train, epochs=20, batch_size=100, verbose=1, validation_data=(X_test, y_test))
 
score = model.evaluate(X_test, y_test, verbose=0)
 
print('Test Loss:{0:.3f}'.format(score[0]))
print('Test accuracy:{0:.3}'.format(score[1]))
#処理時間
print("time:{0:.3f}sec".format(time.time() - startTime))

Train on 60000 samples, validate on 10000 samples
Epoch 1/20
60000/60000 [==============================] - 19s 316us/step - loss: 8.6593 - acc: 0.4610 - val_loss: 8.5520 - val_acc: 0.4685
Epoch 2/20
60000/60000 [==============================] - 18s 308us/step - loss: 8.3443 - acc: 0.4816 - val_loss: 8.3932 - val_acc: 0.4786
Epoch 3/20
60000/60000 [==============================] - 18s 307us/step - loss: 8.2844 - acc: 0.4854 - val_loss: 8.3537 - val_acc: 0.4813
Epoch 4/20
60000/60000 [==============================] - 16s 275us/step - loss: 8.2574 - acc: 0.4873 - val_loss: 8.3666 - val_acc: 0.4802
Epoch 5/20
60000/60000 [==============================] - 15s 257us/step - loss: 8.0335 - acc: 0.5009 - val_loss: 7.5656 - val_acc: 0.5299
Epoch 6/20
60000/60000 [==============================] - 16s 259us/step - loss: 7.0071 - acc: 0.5642 - val_loss: 7.0629 - val_acc: 0.5612
Epoch 7/20
60000/60000 [==============================] - 17s 289us/step - loss: 6.8701 - acc: 0.5731 - val_loss: 6.

# MNIST画像　グレースケール　２値化　0 1.0

In [51]:
'''
データの読み込みと前処理
'''
#データの読み込み
(X_train, y_train), (X_test, y_test) = mnist.load_data()
#訓練データ
#2値化
ret, X_train = cv2.threshold(X_train, 127, 255, cv2.THRESH_BINARY)

X_train = X_train.reshape(60000, 28, 28, 1)

X_train = X_train.astype('float32')#型を変更
X_train /= 255 #0から1.0の範囲に変換

#正解ラベル
correct = 10
y_train = np_utils.to_categorical(y_train, correct)
 
#テストデータ
#2値化
ret, X_test = cv2.threshold(X_test, 127, 255, cv2.THRESH_BINARY)
X_test = X_test.reshape(10000, 28, 28, 1)
X_test = X_test.astype('float32')
X_test /= 255
 
y_test = np_utils.to_categorical(y_test, correct)
print(X_train[0])

[[[0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]]

 [[0.]
  [

In [153]:
'''
CNNの構築
'''
 
model = Sequential()
 
model.add(Conv2D(filters=32, kernel_size=(3,3), padding='same', input_shape=(28, 28, 1), activation='relu'))
model.add(Flatten())
model.add
model.add(Dense(10, activation='softmax'))
 
model.compile(loss='categorical_crossentropy', optimizer=Adam(), metrics=['accuracy'])
 
'''
学習
'''
#計測開始
startTime = time.time()
 
history = model.fit(X_train, y_train, epochs=20, batch_size=100, verbose=1, validation_data=(X_test, y_test))
 
score = model.evaluate(X_test, y_test, verbose=0)
 
timer = time.time() - startTime

#損失
print('Test Loss:{0:.3f}'.format(score[0]))

#精度
print('Test accuracy:{0:.3}'.format(score[1]))

# 処理時間
print("time:{0:.3f}sec".format(timer))

#ファイル出力
with open('MNIST_gray_conv_dense.txt', 'w') as f:
  # 書き込み
  f.writelines('Test Loss:{0:.3f}'.format(score[0])+"\n")
  f.writelines('Test accuracy:{0:.3}'.format(score[1])+"\n")
  f.writelines("time:{0:.3f}sec".format(timer)+"\n")

Train on 60000 samples, validate on 10000 samples
Epoch 1/20
60000/60000 [==============================] - 19s 309us/step - loss: 0.2606 - acc: 0.9263 - val_loss: 0.1073 - val_acc: 0.9686
Epoch 2/20
60000/60000 [==============================] - 18s 305us/step - loss: 0.0853 - acc: 0.9755 - val_loss: 0.0829 - val_acc: 0.9747
Epoch 3/20
60000/60000 [==============================] - 19s 310us/step - loss: 0.0573 - acc: 0.9834 - val_loss: 0.0707 - val_acc: 0.9775
Epoch 4/20
60000/60000 [==============================] - 17s 286us/step - loss: 0.0424 - acc: 0.9873 - val_loss: 0.0684 - val_acc: 0.9778
Epoch 5/20
60000/60000 [==============================] - 16s 261us/step - loss: 0.0326 - acc: 0.9901 - val_loss: 0.0712 - val_acc: 0.9782
Epoch 6/20
60000/60000 [==============================] - 17s 278us/step - loss: 0.0253 - acc: 0.9927 - val_loss: 0.0756 - val_acc: 0.9786
Epoch 7/20
60000/60000 [==============================] - 19s 311us/step - loss: 0.0191 - acc: 0.9948 - val_loss: 0.

In [175]:
import numpy as np
import cv2
from matplotlib import pyplot as plt
#データの読み込み
(X_train, y_train), (X_test, y_test) = mnist.load_data()
#訓練データ
#フーリエ変換
X_train = np.fft.fft2(X_train)
X_train = np.fft.fftshift(X_train)
X_train = 20*np.log(np.abs(X_train))

X_train = X_train.reshape(60000, 28, 28, 1)
X_train = X_train.astype('float32')#型を変更
X_train /= 255 #0から1.0の範囲に変換
print(X_train.max())
print(X_train.shape)
print(type(X_train[0][0][0]))

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:9: RuntimeWarning: divide by zero encountered in log
  if __name__ == '__main__':


0.8849646
(60000, 28, 28, 1)
<class 'numpy.ndarray'>


In [182]:
#データの読み込み
(X_train, y_train), (X_test, y_test) = mnist.load_data()
#訓練データ
#フーリエ変換
X_train = np.fft.fft2(X_train)
X_train = np.fft.fftshift(X_train)

<function ndarray.max>

In [187]:
abs(X_train).min()

0.0

# グレースケール　フーリエ変換

In [188]:
'''
データの読み込みと前処理
'''
#データの読み込み
(X_train, y_train), (X_test, y_test) = mnist.load_data()

#フーリエ変換
X_train = np.fft.fft2(X_train)
X_train = np.fft.fftshift(X_train)
X_train = np.abs(X_train)
X_train = X_train.reshape(60000, 28, 28, 1)
X_train = X_train.astype('float32')#型を変更
X_train /= X_train.max() #0から1.0の範囲に変換

#正解ラベル
correct = 10
y_train = np_utils.to_categorical(y_train, correct)
 
#テストデータ
#フーリエ変換
X_test = np.fft.fft2(X_test)
X_test = np.fft.fftshift(X_test)
X_test = np.abs(X_test)
X_test = X_test.reshape(10000, 28, 28, 1)
X_test = X_test.astype('float32')
X_test /= X_test.max()
 
y_test = np_utils.to_categorical(y_test, correct)

1.0

In [192]:
'''
CNNの構築
'''
 
model = Sequential()
 
model.add(Conv2D(filters=32, kernel_size=(3,3), padding='same', input_shape=(28, 28, 1), activation='relu'))
model.add(Flatten())
model.add
model.add(Dense(10, activation='softmax'))
 
model.compile(loss='categorical_crossentropy', optimizer=Adam(), metrics=['accuracy'])
 
'''
学習
'''
#計測開始
startTime = time.time()
 
history = model.fit(X_train, y_train, epochs=20, batch_size=100, verbose=1, validation_data=(X_test, y_test))
 
score = model.evaluate(X_test, y_test, verbose=0)
 
print('Test Loss:{0:.3f}'.format(score[0]))
print('Test accuracy:{0:.3}'.format(score[1]))
#処理時間
print("time:{0:.3f}sec".format(time.time() - startTime))

Train on 60000 samples, validate on 10000 samples
Epoch 1/20
60000/60000 [==============================] - 19s 314us/step - loss: 2.3018 - acc: 0.1116 - val_loss: 2.3012 - val_acc: 0.1135
Epoch 2/20
60000/60000 [==============================] - 19s 315us/step - loss: 2.3013 - acc: 0.1118 - val_loss: 2.3011 - val_acc: 0.1134
Epoch 3/20
60000/60000 [==============================] - 18s 307us/step - loss: 2.3009 - acc: 0.1126 - val_loss: 2.3020 - val_acc: 0.1129
Epoch 4/20
60000/60000 [==============================] - 19s 312us/step - loss: 2.3004 - acc: 0.1125 - val_loss: 2.3028 - val_acc: 0.1026
Epoch 5/20
60000/60000 [==============================] - 19s 311us/step - loss: 2.2997 - acc: 0.1142 - val_loss: 2.3042 - val_acc: 0.1032
Epoch 6/20
60000/60000 [==============================] - 17s 286us/step - loss: 2.2990 - acc: 0.1165 - val_loss: 2.3044 - val_acc: 0.1033
Epoch 7/20
60000/60000 [==============================] - 17s 284us/step - loss: 2.2976 - acc: 0.1174 - val_loss: 2.

KeyboardInterrupt: 

# グレースケール　フーリエ変換　グレースケール

In [193]:
'''
データの読み込みと前処理
'''
#データの読み込み
(X_train, y_train), (X_test, y_test) = mnist.load_data()

#フーリエ変換
X_train = np.fft.fft2(X_train)
X_train = np.fft.fftshift(X_train)
X_train = np.abs(X_train)
X_train = cv2.cvtColor(X_train, cv2.COLOR_RGB2GRAY)
X_train = X_train.reshape(60000, 28, 28, 1)
X_train = X_train.astype('float32')#型を変更
X_train /= X_train.max() #0から1.0の範囲に変換

#正解ラベル
correct = 10
y_train = np_utils.to_categorical(y_train, correct)
 
#テストデータ
#フーリエ変換
X_test = np.fft.fft2(X_test)
X_test = np.fft.fftshift(X_test)
X_test = np.abs(X_test)
X_test = cv2.cvtColor(X_test, cv2.COLOR_RGB2GRAY)
X_test = X_test.reshape(10000, 28, 28, 1)
X_test = X_test.astype('float32')
X_test /= X_test.max()
 
y_test = np_utils.to_categorical(y_test, correct)

error: /opt/concourse/worker/volumes/live/d8bcd4d1-79b2-4aa5-797a-b95097f1118f/volume/opencv_1512680501887/work/modules/imgproc/src/color.cpp:11010: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cvtColor


In [15]:
i = 0
loss = []
while(i < 5):
    print(i)
    loss.append(i)
    i+=1

0
1
2
3
4


In [22]:
loss

[0, 1, 2, 3, 4]

In [26]:
with open('sample.txt', 'w') as f:
    for x in loss:
        f.write(str(x) + ",")

In [30]:
import pandas as pd
loss = pd.DataFrame(loss)

In [31]:
import pandas as pd
loss = pd.DataFrame(loss)
loss.to_csv("sample.csv", header=False, index=False)

In [34]:
model = Sequential()
 
model.add(Conv2D(filters=32, kernel_size=(3,3), padding='same', input_shape=(28, 28, 1), activation='relu'))
model.add(Flatten())
model.add
model.add(Dense(10, activation='softmax'))
 
model.compile(loss='categorical_crossentropy', optimizer=Adam(), metrics=['accuracy'])

In [40]:
print(model.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_4 (Conv2D)            (None, 28, 28, 32)        320       
_________________________________________________________________
flatten_4 (Flatten)          (None, 25088)             0         
_________________________________________________________________
dense_4 (Dense)              (None, 10)                250890    
Total params: 251,210
Trainable params: 251,210
Non-trainable params: 0
_________________________________________________________________
None


In [43]:
i=10
with open('MNIST_ZeroDL_summary.txt', 'w') as f:
  # 書き込み
  f.writelines(str(i))

In [38]:
import keras
keras.utils.print_summary(model, line_length=None, positions=None, print_fn=None)

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_4 (Conv2D)            (None, 28, 28, 32)        320       
_________________________________________________________________
flatten_4 (Flatten)          (None, 25088)             0         
_________________________________________________________________
dense_4 (Dense)              (None, 10)                250890    
Total params: 251,210
Trainable params: 251,210
Non-trainable params: 0
_________________________________________________________________


In [45]:
import numpy as np
# データの読み込みと前処理
from keras.utils import np_utils
from keras.datasets import mnist
# kerasでCNN構築
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D
from keras.layers import Activation, Dropout, Flatten, Dense
from keras.optimizers import Adam
# 時間計測
import time

import cv2

'''
データの読み込みと前処理
'''
# データの読み込み
(X_train, y_train), (X_test, y_test) = mnist.load_data()
# 訓練データ
# 2値化
ret, X_train = cv2.threshold(X_train, 127, 255, cv2.THRESH_BINARY)

X_train = X_train.reshape(60000, 28, 28, 1)

X_train = X_train.astype('float32')  # 型を変更


# 正解ラベル
correct = 10
y_train = np_utils.to_categorical(y_train, correct)

# テストデータ
# 2値化
ret, X_test = cv2.threshold(X_test, 127, 255, cv2.THRESH_BINARY)
X_test = X_test.reshape(10000, 28, 28, 1)
X_test = X_test.astype('float32')


y_test = np_utils.to_categorical(y_test, correct)



In [47]:
X_train.max()

255.0