In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4])

### 保存

In [3]:
np.save('np_a.npy', a)

## ロード

In [4]:
b = np.load('np_a.npy')

In [5]:
b

array([1, 2, 3, 4])

## 乱数

In [8]:
a = np.random.rand(1,3)

## where インデックスの取得

In [10]:
np.where(a<0.5)

(array([0, 0]), array([0, 2]))

In [11]:
a

array([[0.12855328, 0.85635889, 0.28104693]])

### np.where(条件, 真の場合, 偽の場合)