In [1]:
import numpy as np

# 3章　ニューラルネットワーク

## 活性化関数

In [8]:
x = np.array([1, -2, 0, 2])

In [2]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [9]:
sigmoid(x)

array([0.73105858, 0.11920292, 0.5       , 0.88079708])

In [7]:
def step_function(x):
    return (x>0).astype(int)

In [10]:
step_function(x)

array([1, 0, 0, 1])

In [11]:
def relu(x):
    return np.maximum(0, x)

In [12]:
relu(x)

array([1, 0, 0, 2])

## 3層ニューラルネットワーク

In [38]:
X = np.array([1.0, 0.5])
W1 = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
B1 = np.array([0.1, 0.2, 0.3])

In [39]:
a = np.dot(X, W1) + B1

In [40]:
a = sigmoid(a)

In [41]:
W2 = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
B1 = np.array([0.1, 0.2])

In [42]:
a2 = np.dot(a, W2) + B1

In [43]:
a2 = sigmoid(a2)

In [44]:
W3 = np.array([[0.1, 0.3], [0.2, 0.4]])
B3 = np.array([0.1, 0.2])

In [45]:
o = np.dot(a2, W3) + B3

In [46]:
o

array([0.31682708, 0.69627909])

In [51]:
class Net():
    def __init__(self):
        self.network = {}
        self.network['W1'] = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
        self.network['b1'] = np.array([0.1, 0.2, 0.3])
        self.network['W2'] = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
        self.network['b2'] = np.array([0.1, 0.2])
        self.network['W3'] = np.array([[0.1, 0.3], [0.2, 0.4]])
        self.network['b3'] = np.array([0.1, 0.2])
        
    def forward(self, x):
        W1, W2, W3 = self.network['W1'], self.network['W2'], self.network['W3']
        b1, b2, b3 = self.network['b1'], self.network['b2'], self.network['b3']
        
        a1 = np.dot(x, W1) + b1
        z1 = sigmoid(a1)
        a2 = np.dot(z1, W2) + b2
        z2 = sigmoid(a2)
        a3 = np.dot(z2, W3) + b3
        y = a3
        return y

In [52]:
x = np.array([0.1, 0.5])

In [53]:
net = Net()

In [54]:
y = net.forward(x)

In [55]:
y

array([0.31234736, 0.6863161 ])

# 4章ニューラルネットワークの学習