In [1]:
import numpy as np

# 3章　ニューラルネットワーク

## 活性化関数

In [8]:
x = np.array([1, -2, 0, 2])

In [2]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [9]:
sigmoid(x)

array([0.73105858, 0.11920292, 0.5       , 0.88079708])

In [7]:
def step_function(x):
    return (x>0).astype(int)

In [10]:
step_function(x)

array([1, 0, 0, 1])

In [11]:
def relu(x):
    return np.maximum(0, x)

In [12]:
relu(x)

array([1, 0, 0, 2])

## 3層ニューラルネットワーク

In [38]:
X = np.array([1.0, 0.5])
W1 = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
B1 = np.array([0.1, 0.2, 0.3])

In [39]:
a = np.dot(X, W1) + B1

In [40]:
a = sigmoid(a)

In [41]:
W2 = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
B1 = np.array([0.1, 0.2])

In [42]:
a2 = np.dot(a, W2) + B1

In [43]:
a2 = sigmoid(a2)

In [44]:
W3 = np.array([[0.1, 0.3], [0.2, 0.4]])
B3 = np.array([0.1, 0.2])

In [45]:
o = np.dot(a2, W3) + B3

In [46]:
o

array([0.31682708, 0.69627909])

In [51]:
class Net():
    def __init__(self):
        self.network = {}
        self.network['W1'] = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
        self.network['b1'] = np.array([0.1, 0.2, 0.3])
        self.network['W2'] = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
        self.network['b2'] = np.array([0.1, 0.2])
        self.network['W3'] = np.array([[0.1, 0.3], [0.2, 0.4]])
        self.network['b3'] = np.array([0.1, 0.2])
        
    def forward(self, x):
        W1, W2, W3 = self.network['W1'], self.network['W2'], self.network['W3']
        b1, b2, b3 = self.network['b1'], self.network['b2'], self.network['b3']
        
        a1 = np.dot(x, W1) + b1
        z1 = sigmoid(a1)
        a2 = np.dot(z1, W2) + b2
        z2 = sigmoid(a2)
        a3 = np.dot(z2, W3) + b3
        y = a3
        return y

In [52]:
x = np.array([0.1, 0.5])

In [53]:
net = Net()

In [54]:
y = net.forward(x)

In [55]:
y

array([0.31234736, 0.6863161 ])

# 4章ニューラルネットワークの学習

## 学習アルゴリズムのステップ

### 1. ミニバッチ
訓練データの中からランダムに一部のデータを選び出す。その選ばれたデータをミニバッチという。

### 2. 勾配計算
各重みパラメータの勾配を求める

### 3. パラメータの更新
重みパラメータを勾配方向に更新する

### 4. 繰り返す
指定回数繰り返す

## 勾配法
$$
x_0 = x_0 - \eta \frac{\partial f}{\partial x_0}
$$

## 2層ニューラルネットワーク

In [ ]:
class 

# 5章　誤差逆伝播法

In [1]:
class Affine:
    def __init__(self, W, b):
        self.W = W
        self.b = b
        self.x = None
        self.dW = None
        self.db = None
        
    def forward(self, x):
        self.x = x
        out = np.dot(x, self.W) + self.b
        
        return out
    
    def backward(self, dout):
        dx = np.dot(dout, self.W.T)
        self.dW = np.dot(self.x.T, dout)
        self.db = np.sum(dout, axis=0)
        
        return

In [2]:
class SoftmaxWithLoss:
    def __init__(self):
        self.loss = None
        self.y = None
        sel.t = None
        
    def forward(self, x, t):
        self.t = t
        self.y = softmax(x)
        self.loss = cross_entropy_error(self.y, self.t)
        
        return self.loss
    
    def backward(self, dout=1):
        batch_size = self.t.shape[0]
        
        dx = (self.y - self.t) /batch_size
        
        return dx

In [ ]:
class TwoLayerNet:
    
    def __init__(self, input_size, hidden_size, output_size, weight_init_std = 0.01):
        #==== 重みの初期化 ====
        
        #==== レイヤーの生成
        
    
    def predict(self, x):
        
        return None
    
    def loss(self, x, t):
        y = self.predict(x)
        
        #Loss Function
        L = Loss(y, t)
        return L
    
    def numerical_gradient(self, x, t):
        loss_W = lambda W: self.loss(x, t)
        
        grads = {}
        
        return grads
    
    def gradient(self, x, t):
        #forward
        self.loss(x,t)
        
        #backward
        
        